name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*  # Trigger on feature branches
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Client Docker image
        working-directory: client
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-crud:client-$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-crud:client-$GITHUB_SHA

      - name: Build and push Server Docker image
        working-directory: server
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-crud:server-$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}mern-crud:server-$GITHUB_SHA

  deploy_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to DEV
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-crud:dev-client$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-crud:dev-client-$GITHUB_SHA
      - name: Build and push Server Docker image
        working-directory: server
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-crud:dev-server-$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-crud:dev-server-$GITHUB_SHA

  deploy_stg:
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Deploy to STG
        run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-crud:stg-client$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-crud:stg-client-$GITHUB_SHA
      - name: Build and push Server Docker image
        working-directory: server
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-crud:stg-server-$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-crud:stg-server-$GITHUB_SHA
  deploy_prod:
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Update Image tag
        run: |
          sed -i 's/^imageTag: .*/imageTag: ${{ github.sha }}/g' ./client/values.yaml
          sed -i 's/^imageTag: .*/imageTag: ${{ github.sha }}/g' ./server/values.yaml
          git config --global user.email "bikash.bhandari1986@gmail.com"
          git config --global user.name "Bikash Bhandari"
          git add ./client/values.yaml
          git add ./server/values.yaml
          git commit -m "Updating image tag with latest build number."
          
      - name: Deploy to PROD
        run: |
          # Add deployment command here for PROD environment
