name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Client Docker image
        working-directory: client
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/client .
          docker push ${{ secrets.DOCKER_USERNAME }}/client
      
      - name: Build and push Backend Docker image
        working-directory: server
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend
      
      - name: Build and push MongoDB Docker image
        working-directory: mongodb
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mongodb .
          docker push ${{ secrets.DOCKER_USERNAME }}/mongodb
