name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: jslbikash
          password: dckr_pat_6mFiQ5BgAlZWxJkpWRxN82vylS4
      
      - name: Build and push Client Docker image
        run: |
          pwd
          ls
          cd client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/client:$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/client:$GITHUB_SHA
      
      - name: Build and push Server Docker image
        run: |
          cd server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/server:$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/server:$GITHUB_SHA
